// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYe76ANrVmXQhOv7ZB3sNtt8AP2Uy2W5A',
    appId: '1:534098960729:web:bf8ac9a4b40728d5a7ac48',
    messagingSenderId: '534098960729',
    projectId: 'project-comapp',
    authDomain: 'project-comapp.firebaseapp.com',
    storageBucket: 'project-comapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYe76ANrVmXQhOv7ZB3sNtt8AP2Uy2W5A',
    appId: '1:534098960729:android:bf8ac9a4b40728d5a7ac48',
    messagingSenderId: '534098960729',
    projectId: 'project-comapp',
    storageBucket: 'project-comapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYe76ANrVmXQhOv7ZB3sNtt8AP2Uy2W5A',
    appId: '1:534098960729:ios:bf8ac9a4b40728d5a7ac48',
    messagingSenderId: '534098960729',
    projectId: 'project-comapp',
    storageBucket: 'project-comapp.firebasestorage.app',
    iosBundleId: 'com.example.flutter_application_1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYe76ANrVmXQhOv7ZB3sNtt8AP2Uy2W5A',
    appId: '1:534098960729:macos:bf8ac9a4b40728d5a7ac48',
    messagingSenderId: '534098960729',
    projectId: 'project-comapp',
    storageBucket: 'project-comapp.firebasestorage.app',
    iosBundleId: 'com.example.flutter_application_1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYe76ANrVmXQhOv7ZB3sNtt8AP2Uy2W5A',
    appId: '1:534098960729:windows:bf8ac9a4b40728d5a7ac48',
    messagingSenderId: '534098960729',
    projectId: 'project-comapp',
    storageBucket: 'project-comapp.firebasestorage.app',
  );
}